#!/usr/bin/env bash
# A script to print record type and destination of subdomains
print_subdomain() {
    local domain="$1"
    local subdomain="$2"
    local record
    local destination

    record=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk '/IN/ { print $4 }')
    destination=$(dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | awk '/IN/ { print $5 }')
    echo "The subdomain $2 is a $record record and points to $destination"
}

# Check the number of arguments
if [ $# -eq 2 ]; then
    # Both domain and subdomain parameters are provided
    print_subdomain "$1" "$2"
elif [ $# -eq 1 ]; then
    # Only domain parameter is provided, display information for specific subdomains
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        print_subdomain "$1" "$subdomain"
    done
fi
