#!/usr/bin/env bash
# install nginx and configures it to listen on port 80  and querying return
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.html
service nginx restart
