#!/usr/bin/env bash
# configure a brand new ubuntu machine/nginx server sothe /redirect_me
# is redirected to another page using a 301 redirection | Permanent redirection

NGINX_CONF="/etc/nginx/sites-available/default"
HTML_DIR="/etc/nginx/html"

apt-get update
apt-get install -y nginx

mkdir -p $HTML_DIR
touch $HTML_DIR/index.html

echo "Hello World!" > $HTML_DIR/index.html
printf %s "server {
    listen        80 default_server;
    listen        [::]:80 default_server;
    root          $HTML_DIR;
    index         index.html index.htm;

    location /redirect_me {
        return 301 https://www.frontendmentor.io/profile/gbabohernest;
    }
}
" > $NGINX_CONF

service nginx restart
