#!/usr/bin/env bash
# configure a nginx server to have a custom 404 page
# that contains the string Ceci n'est pas une page.

NGINX_CONF="/etc/nginx/sites-available/default"
HTML_DIR="/etc/nginx/html"

apt-get update
apt-get install -y nginx

mkdir -p $HTML_DIR
touch $HTML_DIR/index.html

echo "Hello World!" > $HTML_DIR/index.html

printf %s "server {
    listen        80 default_server;
    listen        [::]:80 default_server;
    root          $HTML_DIR;
    index         index.html index.htm;

    location /redirect_me {
        return 301 https://www.frontendmentor.io/profile/gbabohernest;
    }
}
" > sudo tee $NGINX_CONF

# 404 page creation
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$string_for_replacement/" $NGINX_CONF

sudo service nginx restart
