#!/usr/bin/env bash
# A script that generates a MYSQL dump and creates a compressed archive out of it to backup.

dump_file="backup.sql"
archive_name="$(date +'%d-%m-%Y').tar.gz"
mysql_password="$1"

mysqldump -uroot -p"$mysql_password" --all-databases > "$dump_file"
tar -cz "$archive_name" "$dump_file"
