#!/usr/bin/env bash
# Debugs error, make Nginx to listen on port 80, address issue where sites-available/default is unlinked to sites-enabled/default.
ln -sfn /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
sed -i 's|pid /run/nginx.pid|pid /run/nginx_pid|' /etc/nginx/nginx.conf
