#!/usr/bin/env bash
# Debugs error, make Nginx to listen on port 80, address issue where sites-available/default is unlinked to sites-enabled/default.
grep -q 'sites-enabled/default' /etc/nginx/nginx.conf || sed -i '/sites-enabled\/default/s/^#//g' /etc/nginx/nginx.conf
ln -sfn /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
