#!/usr/bin/env bash
# This script indefinitely write "I am alive" to the file /tmp/my_process.
#  pause two seconds in between messages

while true
do
    echo "I am alive!" >> /tmp/my_process
    sleep 2
done
