#!/usr/bin/env bash
# This script displays the content of the file /etc/passwd.

while IFS= read -r line
do
    # Extracting the fields, but not storing them in variables.
    echo "Username: $(echo "$line" | cut -d ":" -f1)"
    echo "User ID: $(echo "$line" | cut -d ":" -f4)"
    echo "Home Directory: $(echo "$line" | cut -d ":" -f6)"

done < "/etc/passwd"
