#!/usr/bin/env bash
# This script display "Best School" 10 times
# on 9th iteration, it diplay Hi

count=1

while [ $count -le 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi

	count=$((count + 1))
done
