#!/usr/bin/env bash
# This script display "Best School" for other iterations/
# "bad luck" for for the 4th iteration
# "good luck" for the 8th iteration

count=1

while [ $count -le 10 ]; do
	if [ $count -eq 4 ]; then
		echo "bad luck"
	elif [ $count -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	count=$((count + 1))
done
