#!/usr/bin/env bash
# This script display Hours from 0 - 12
# Display minutes from 1 - 59

hour=0

while [ $hour -le 12 ]
do
	minutes=1
	echo "Hour": $hour
	while [ $minutes -le 59 ]
	do
		# echo "Hour: $hour"
		echo "$minutes"
		minutes=$((minutes + 1))
	done
	hour=$((hour + 1))
done
