#!/usr/bin/env bash
# Configure ufw so that it blocks all incoming traffic, except the following TCP ports: 
# 22 (SSH)
# 443 (HTTPS SSL)
# 80 (HTTP)


# Check if the script is run as root
if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# Install ufw if not already installed
apt-get update
apt-get install -y ufw

ufw disable
ufw enable

ufw default deny incoming
ufw default allow outgoing

ufw allow 22/tcp
ufw allow 443/tcp
ufw allow 80/tcp

ufw status
