#!/usr/bin/env bash
# This script configures an Ubuntu server
#  changes IP address of localhost and facebook
awk '!/localhost|facebook\.com/' /etc/hosts > ~/hosts.new
echo "127.0.0.2		localhost" >> ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
