#!/usr/bin/env bash
# Get Apache to run on container and return a page containing
# Hello Holberton when querying the root of it
apt-get -y update
apt-get -y install apache2
echo "ServerName localhost" >> sudo tee -a /etc/apache2/apache2.conf
echo "Hello Holberton"
service apache2 start
