#!/usr/bin/env bash
# A script that configures a container so that Nginx is running as the nginx user.

chown -R nginx:nginx /var/run/nginx /var/log/nginx /etc/nginx /usr/share/nginx/html
sed -i 's/user  nginx;/user  nginx nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen       80;/listen       8080;/' /etc/nginx/conf.d/default.conf
su nginx service nginx restart
