#!/usr/bin/env bash
# A script that configures a container so that Nginx is running as the nginx user.

# Change ownership of configuration files
chown nginx:nginx /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/sites-available/default

# chown -R nginx:nginx /var/run/nginx /var/log/nginx /etc/nginx /usr/share/nginx/html

# Set appropriate permissions on configuration files
chmod 644 /etc/nginx/nginx.conf
chmod 644 /etc/nginx/sites-available/default

# modify nginx.conf & change default server block
sed -i 's/#user www-datat;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

pkill apache2

su -s /bin/sh -c "service nginx restart" nginx
