#!/usr/bin/env bash
# A script that configures a container so that Nginx is running as the nginx user.
chown nginx:nginx /etc/nginx/nginx.conf /etc/nginx/sites-available/default
chmod u+rwx /etc/nginx/nginx.conf /etc/nginx/sites-available/default
sed -i 's/80/8080/' /etc/nginx/sites-available/default
pkill apache2
su -s /bin/sh -c "service nginx restart" nginx
